FORMAT: 1A
HOST: http://hotmail.com

# 오라클 아레나 Chatbot Backend API
오라클 아레나 Chatbot Application 데모세션을 위한 API 디자인 프로젝트입니다.

Author: philip.kim@oracle.com

## Seats Collection [/seats]
경기장내 좌석에 관한 API

### List All Seats [GET]
모든 좌석과 예매 가능여부를 목록으로 Return 합니다.

+ Response 200 (application/json)

        [
            {
                "section": "Section 114",
                "row": "3",
                "available": true,
                "price": 299,
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/D2BA28E8C506DC0CDA4F9C14F6C3FF17C1177E4725F3?allowInterrupt=1"
                }
            },
            {
                "section": "Section 216",
                "row": "7",
                "available": true,
                "price": 219,
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/D2BA28E8C506DC0CDA4F9C14F6C3FF17C1177E4725F3?allowInterrupt=1"
                }
            },
            {
                "section": "Section 229",
                "row": "12",
                "available": true,
                "price": 146,
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/DF03AD812F69F02A82C04FC2F6C3FF17C1177E4725F3?allowInterrupt=1"
                }
            }
        ]

### 좌석예약 [POST]
지정한 좌석을 예약하는 Method 입니다.  Korean 데모를 위해 임시로 만들어졌습니다.

+ Response 200 (application/json)


## Beers Collection [/beers]
경기장에서 판매하는 맥주에 관한 API

### List All Beers [GET]

오라클 라운지에서 제공하는 모든 맥주들을 Return 합니다.

+ Response 200 (application/json)

        [
            {
                "name": "Guinness",
                "description": "No preservatives or additives. 100% natural, ingredients create a unique flavour",
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/D2680B911AEB03B8C3B6EF22F6C3FF17C1177E4725F3?dRevLabel=LATEST&allowInterrupt=1"
                }
            },
            {
                "name": "Pilsner Urquell",
                "description": "World's first pilsner. Grainy malt center with a light touch of butter flavor",
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/D38CC50D762E50731F505711F6C3FF17C1177E4725F3?dRevLabel=LATEST&allowInterrupt=1"
                }
            },
            {
                "name": "Schlappe-Seppel",
                "description": "Smooth bitter, tangy, fruity, full-bodied - more than a beer, it's an attitude",
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/DFE12285193404897A6331F4F6C3FF17C1177E4725F3?dRevLabel=LATEST&allowInterrupt=1"
                }
            },
            {
                "name": "Heineken",
                "description": "Crisp, clean and refreshing, this popular beer is a classic European style Lager",
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/DE79A523EC91B0687D5AA852F6C3FF17C1177E4725F3?dRevLabel=LATEST&allowInterrupt=1"
                }
            },
            {
                "name": "Löwenbräu",
                "description": "This all natural beer is fully balanced with dry but crisp, bitter undertones",
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/DA09DF49105AB60AFEBAC1E0F6C3FF17C1177E4725F3?allowInterrupt=1"
                }
            },
            {
                "name": "Brooklyn Beer",
                "description": "This is a beer from NYC",
                "link": {
                    "rel": "image",
                    "href": "https://publicdocs-corp.documents.us2.oraclecloud.com/documents/link/LF7206C60A9212DA72124CA9F6C3FF17C1177E4725F3/file/DA09DF49105AB60AFEBAC1E0F6C3FF17C1177E4725F3?allowInterrupt=1"
                }
            },
            
        ]